### PR TITLE
PHP7 support

### PR DESCRIPTION
**Pull request by afk11**

### CODE REVIEW

**Comment by afk11** [comment]
Oh wow, wasn't expecting it to be merged that quickly :) I might follow up with some tweaks. meant to update https://github.com/sop/crypto-types/pull/1 with notes actually..

**Comment by sop** [comment]
You're welcome! I decided to start from the tiniest one. Scrutinizer appears to nag about something, i'll look into that. Glad you're up for help! :)

**Comment by afk11** [comment]
Hmm, that's a strange one.. though it does have a note at the top:

> Usage of our globally installed phpunit version is deprecated.
Instead, consider adding a dev dependency to your project:
composer require --dev phpunit/phpunit

We could just add it as a dev dependency to each repo's composer.json? Been avoiding committing it until now, but think it makes sense to pick a tag for our tests.

**Comment by sop** [comment]
Yeah figured that it's best to use bundled phpunit. I think the globally installed one is deliberately old. I've added `vendor/bin/phpunit` to configurations now.

**Pull request merged**
